### ISSUE TITLE
Documentation (minor) bug

### ISSUE THREAD

**Issue by amittendulkar** [kopoli/robot-mode#13]
Please correct the missing backquote (in place of single quote) in the below description in README.md

![image](https://github.com/kopoli/robot-mode/assets/18111340/3a1d4e39-f214-480f-9fa0-c6d34aa27e9e)

**Comment by kopoli** [comment]
Thanks for reporting !

Removed the keybinding quoting altogether. I could not find any instance of this style quoting in other packages, so it is better to be removed.

**Comment by amittendulkar** [comment]
I think you can keep it as the key binding stands out for the reader. Here is where Elpy repository is using it,

https://github.com/jorgenschaefer/elpy?tab=readme-ov-file#quickstart

We can close the issue once you merge either approach fix to main.
