### ISSUE TITLE
interested in getting conditional blocks to indent

### ISSUE THREAD

**Issue by atmalagon** [kopoli/robot-mode#2]
Hi!
Really appreciate this project; have been using it on emacs and it makes working on robot framework much easier. Just noticed that the formatting doesn't indent statements within conditional blocks (FOR/IF/WHILE/TRY, etc) - is that something you could add or point me to how to augment in the el file?

Thanks!

**Comment by kopoli** [comment]
Hi,
Thanks for your interest!

There are quite a few of different control structures in robot framework:
https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#control-structures

The current indenting function is quite simple. It is the `robot-mode-indent-line` function. Currently there are only two levels of indentation (either none or one level). 

I have to think about how a nested (multi-level) indentation would be handled from the user's perspective. Currently the indentation just toggles between the two levels. Maybe a similar indentation level switcher that e.g. the python-mode has?

Also, it would be good to have some syntax highlighting for those control structures (IF/ELSE/FOR etc.)

**Comment by kopoli** [comment]
I added nested indentation in #3. It works at least in my test environment.

The indentation is still only toggleable: Zero or correct amount of indent. I.e. there is no "scrolling" of different indentation levels as in python-mode.

Does this work in your environment ?

**Comment by atmalagon** [comment]
Hi kopoli, this is awesome, thank you so much! I tested it out just now and am seeing that the first line underneath a FOR/IF/WHILE/TRY gets indented correctly! It seems though that additional lines in the body start at 1 space and don't indent even if I do Ctrl-C Ctrl+A. END doesn't automatically get put at the same indent level as the opening structure when I type it out but with the formatting Ctrl-C + Ctrl-A it does, which is great. Are you seeing the same behavior for the 2nd-nth lines in a conditional structure (they don't have the same indent level as the first line)?

**Comment by kopoli** [comment]
To be honest, I didn't test the `C-c C-a` functionality at all :sweat_smile: 

Now that I tested it, it seems to work. Though, it first aligns everything and only then indents the lines. This causes words in different indentation levels to be aligned differently. However, such behaviour is present in the official docs as well:

https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#basic-while-syntax


Regarding the improper indentation of the second line. I am not able to reproduce it. E.g. the following buffer contents:

```
*** Test cases ***
Conditionals keyword
IF              ABC
Set Variable    ${ARG}
Set Variable    ${ARG}
ELSE IF         CDE
Set Variable    ${ARG2}
ELSE
Set Variable    ${ARG3}
END
```
Is indented in the following way (By doing `C-x h C-c C-a`):

```
*** Test cases ***
Conditionals keyword
    IF              ABC
        Set Variable    ${ARG}
        Set Variable    ${ARG}
    ELSE IF         CDE
        Set Variable    ${ARG2}
    ELSE
        Set Variable    ${ARG3}
    END
```

Do you have an example that is indented incorrectly ?
(With the 1 space, and mis-aligned END line.)


The logic of indenting a block is the following:
- IF/FOR/WHILE/TRY is indented to the same level as the previous line.
- First line after is indented `robot-mode-basic-offset` + the previous line's indent.
- The second line is indented to the same level as the previous line.

I.e. in the normal case if you indent a line to whatever indent, then the following line should automatically indent to that same level.

**Comment by atmalagon** [comment]
Shoot, I still get the same behavior, most peculiar. I took the buffer example above and C-c C-a'ed it to get:
```
*** Test Cases ***
Conditionals keyword
    IF	     ABC
	Set Variable	${ARG}
 Set Variable		${ARG}
    ELSE IF	     CDE
	Set Variable	${ARG2}
    ELSE
	Set Variable	${ARG3}
    END
```    
I'm on emacs 28.1 (on Apple) if that might be relevant? It seems like something is overwriting robot-mode-offset to be 1 for that second Set Variable line, somehow.

**Comment by kopoli** [comment]
I tested this with emacs 28.1, but the behaviour was the same (as with newer emacs from git).

The only thing that caused wonkiness in the indentation was if the `indent-tabs-mode` is non-nil. (There the IF/ELSE... -lines were indented improperly.)

I see that in your output the IF/ELSE... -lines are indented with 4 spaces, and the first line is indented with a single tab. The second line that has the wrong indent, is, however, aligned properly (with a tab). Is your `indent-tabs-mode` `t` ?

Unfortunately I have not tested this much with tab indentation.

Could you test disabling the `indent-tabs-mode` in that buffer with the following:

```
C-: (setq indent-tabs-mode nil)
```

And see if the problem persists?

**Comment by kopoli** [comment]
Actually, with the `indent-tabs-mode` as `t`, I was able to reproduce the problem !

Now looking at it, I think that the problem is that when the first line after IF is indented with a single tab-character, the second line adds the same amount of space characters as there are whitespace characters in the previous line (1 character). I'll take a look how the logic should work now with tabs enabled.

**Comment by kopoli** [comment]
I updated the latest commit in #3. It now should work with tabs. The fix was to calculate indentation `string-width` instead of character count.

Could you check it if it works for you?

There is still some wonkiness if the buffer is changed from tabs <-> spaces indentation, but that is probably to be expected.

**Comment by atmalagon** [comment]
It works!!! Thank you so much! Hooray :)))

**Comment by kopoli** [comment]
Thanks for testing the changes!

I pushed the changes of #3 to master, and bumped the version to 0.7.0. This new version should be available via MELPA and MELPA-stable in the near future.
