### ISSUE TITLE
What do you do for auto completion?

### ISSUE THREAD

**Issue by smahm006** [kopoli/robot-mode#4]
Hey not sure where to ask this but thanks a lot for this mode. I was wondering if there is any language server or mode you use to get autocomplete suggestions?

**Comment by kopoli** [comment]
Sorry, I completely forgot to answer this. 

With my level of usage, I have made do with just `company-mode`.

**Comment by BrachystochroneSD** [comment]
You can install `robotframework-lsp` from `pip`. It integrate very well with `robot-mode` and `eglot`.
You need to add the executable to the list for eglot:
```emacs-lisp
(add-to-list 'eglot-server-programs '(robot-mode . ("robotframework_ls")))
```

**Comment by BrachystochroneSD** [comment]
In fact, adding it in the package would be interesting. 
Something like:
```emacs-lisp
(with-eval-after-load 'eglot
  (defvar eglot-server-programs)
  (push (cons 'robot-mode '("robotframework_ls"))
        eglot-server-programs))
```
